# Generated by Django 6.0.3 on 2026-03-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "jti",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="user_auth.user",
                    ),
                ),
            ],
        ),
    ]
