# Generated by Django 6.0.3 on 2026-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_refreshtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
