# Generated by Django 6.0.3 on 2026-03-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_alter_permission_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="user_auth.role",
            ),
        ),
    ]
