# Generated by Django 6.0.3 on 2026-03-24 18:04

import django.db.models.deletion
import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=user_auth.models.get_default_role_pk,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="user_auth.role",
            ),
        ),
    ]
