@BASE_URL = http://localhost:8000/api/v1
@ACCESS_TOKEN = access
@REFRESH_TOKEN = refresh

###

GET {{BASE_URL}}/users/
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST {{BASE_URL}}/refresh/
Content-Type: application/json

{
  "refresh_token": "{{REFRESH_TOKEN}}"
}

###

POST {{BASE_URL}}/logout/
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST {{BASE_URL}}/users/
Content-Type: application/json

{
  "first_name": "Люд",
  "last_name": "Петрова",
  "email": "ludaaa.petrova@example.com",
  "password": "123",
  "password_confirm": "13",
  "role": 1
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "email": "lu.petrova@example.com",
  "password": "12"
}

###

PATCH {{BASE_URL}}/users/8/
Content-Type: application/json

{
  "password": "12",
  "password_confirm": "12"
}

###

DELETE {{BASE_URL}}/users/5/