@BASE_URL = http://localhost:8000/api/v1
@ACCESS_TOKEN = access
@REFRESH_TOKEN = refresh

###

GET {{BASE_URL}}/users/
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST {{BASE_URL}}/refresh/
Content-Type: application/json

{
  "refresh_token": "{{REFRESH_TOKEN}}"
}

###

POST {{BASE_URL}}/logout/
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST {{BASE_URL}}/register/
Content-Type: application/json

{
  "first_name": "Люд",
  "last_name": "Петрова",
  "email": "ludaaa.petrova@example.com",
  "password": "123",
  "password_confirm": "13",
  "role": 1
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "email": "ludaa.petrova@example.com",
  "password": "123"
}

###

PATCH {{BASE_URL}}/update/
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "password": "1",
  "password_confirm": "1"
}

###

DELETE {{BASE_URL}}/delete/
Authorization: Bearer {{ACCESS_TOKEN}}

###

GET {{BASE_URL}}/mocks/
Authorization: Bearer {{ACCESS_TOKEN}}

###

GET {{BASE_URL}}/mocks/1
Authorization: Bearer {{ACCESS_TOKEN}}

###

POST {{BASE_URL}}/mocks/
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{}

###

PATCH {{BASE_URL}}/mocks/1/
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{}

###

DELETE {{BASE_URL}}/mocks/1/
Authorization: Bearer {{ACCESS_TOKEN}}